// Created by Codex.
// Licensed under the MIT License. See LICENSE file for details.

#pragma once

#include "EngineContext.hpp"
#include "ecs/Entity.hpp"
#include "ecs/VehicleRig1Component.hpp"

#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>
#include <nlohmann/json.hpp>
#include <cstdint>
#include <string>
#include <vector>

namespace eeng::ecs
{
    enum class WheelColliderType : std::uint8_t
    {
        Sphere = 0,
        Capsule = 1
    };

    // VehicleRig1 prototype: per-wheel setup data (POD-style for easy tweaking).
    struct VehicleRig1WheelSpec
    {
        // Chassis-local mount position for this wheel (suspension top).
        glm::vec3 mount_local{ 0.0f };
        // Use mount_local directly; otherwise derive mount from chassis half-extents + mount_sign.
        bool mount_override = false;
        // Per-wheel sign used when deriving mounts from chassis size (X,Z).
        glm::vec2 mount_sign{ 1.0f, 1.0f };
        // Suspension axis in chassis local space (points along wheel travel).
        glm::vec3 suspension_axis{ 0.0f, -1.0f, 0.0f };
        // Wheel axle axis in wheel/knuckle local space.
        glm::vec3 axle_axis{ 0.0f, 0.0f, 1.0f };

        // Wheel-local anchor (useful if origin is not the hub center).
        glm::vec3 wheel_local_anchor{ 0.0f };

        // Suspension rest length along suspension_axis (positive along the axis).
        float suspension_rest_length = 0.0f;
        // Total suspension travel distance (symmetric around rest length).
        float suspension_travel = 0.5f;

        // Optional 6DoF linear limit override in constraint frame (X/Y/Z).
        // X is the suspension axis in our frame setup.
        bool use_linear_limits = false;
        glm::vec3 linear_limit_min{ 0.0f };
        glm::vec3 linear_limit_max{ 0.0f };
        // Optional per-axis equilibrium override (0/1 enabled flags).
        // Note: X is the suspension axis in the constraint frame.
        glm::vec3 linear_equilibrium_enabled{ 0.0f };
        glm::vec3 linear_equilibrium_target{ 0.0f };

        // Suspension spring/damper (6DoF spring on X).
        float spring_k = 15000.0f;
        float spring_d = 1500.0f;

        // Defaults for autogenerated colliders.
        WheelColliderType wheel_collider_type = WheelColliderType::Sphere;
        float wheel_radius = 0.35f;
        float wheel_width = 0.25f;
        float knuckle_radius = 0.15f;
        // Optional mass override (kg). Set <= 0 to keep auto-mass.
        float wheel_mass = 1.0f;
        float knuckle_mass = 1.0f;

        // Optional wheel friction override (PhysicsMaterialComponent).
        bool friction_override = false;
        float wheel_friction = 0.5f;

        bool steerable = false;
        bool driven = false;
        // Override the global drive default (when false, uses VehicleRig1Spec::drive_default).
        bool drive_override = false;
        // Optional sign flips to match art/axis conventions.
        float drive_direction = 1.0f;
        float steer_direction = 1.0f;

        // Optional pre-existing wheel entity (if bound, builder will reuse it).
        EntityRef wheel{};
    };

    // VehicleRig1 prototype: full rig spec.
    struct VehicleRig1Spec
    {
        // Required chassis entity ref (must resolve to a live entity).
        EntityRef chassis{};
        // Optional root entity for grouping (if unbound, a new root is created).
        EntityRef root{};

        // Naming / grouping.
        std::string name_prefix = "VehicleRig1";
        std::string chunk_tag = "vehicle_rig1";
        std::vector<VehicleRig1WheelSpec> wheels;

        // Constraint tuning (disable collisions between constrained bodies).
        bool disable_collisions = true;

        // Default drive flag (used when a wheel does not override).
        bool drive_default = false;
        // Default wheel friction (used when a wheel does not override).
        float wheel_friction = 0.5f;

        // Steering axis in chassis local space.
        glm::vec3 steer_axis{ 0.0f, 1.0f, 0.0f };
        float steer_limit = 0.8f; // radians

        // Chassis collider size (half extents).
        glm::vec3 chassis_half_extents{ 1.6f, 0.35f, 1.0f };

        // Optional model asset names (lookup via ResourceManager asset index).
        std::string chassis_model_name{};
        std::string wheel_model_name{};
        std::string knuckle_model_name{};
    };

    // VehicleRig1 prototype: chassis spawn data (used by prefab generation).
    struct VehicleRig1ChassisSpec
    {
        glm::vec3 position{ 0.0f, 2.0f, 0.0f };
        glm::quat rotation{ 1.0f, 0.0f, 0.0f, 0.0f };
        glm::vec3 half_extents{ 1.6f, 0.35f, 1.0f };
        float mass = 10.0f;
        float linear_damping = 0.2f;
        float angular_damping = 0.4f;
        bool auto_mass = false;
    };

    // VehicleRig1 prototype: runtime rig handles.
    struct VehicleRig1Rig
    {
        EntityRef root{};
        EntityRef chassis{};

        struct WheelRig
        {
            EntityRef knuckle{};
            EntityRef wheel{};
            EntityRef suspension_6dof{};
            EntityRef axle_hinge{};
        };

        std::vector<WheelRig> wheels;
    };

    // Build the VehicleRig1 rig using a split suspension (6DoF + axle hinge).
    VehicleRig1Rig build_vehicle_rig1(EngineContext& ctx, const VehicleRig1Spec& spec);

    // Generate a prefab JSON (top-down entity array) for VehicleRig1 using a scratch registry.
    nlohmann::json build_vehicle_rig1_prefab_json(
        EngineContext& ctx,
        const VehicleRig1Spec& rig_spec,
        const VehicleRig1ChassisSpec& chassis_spec);
} // namespace eeng::ecs
