// Created by Codex.
// Licensed under the MIT License. See LICENSE file for details.

#pragma once

#include "EngineContext.hpp"
#include "ecs/Entity.hpp"
#include "ecs/VehicleRigComponent.hpp"

#include <glm/glm.hpp>
#include <string>
#include <vector>

namespace eeng::ecs
{
    // Data-only spec for a vehicle rig. Keep this POD-like for future prefab/JSON use.
    struct VehicleWheelSpec
    {
        // Chassis local mount position for this wheel (e.g. suspension top).
        glm::vec3 mount_local{ 0.0f };
        // Suspension axis in chassis local space.
        glm::vec3 suspension_axis{ 0.0f, -1.0f, 0.0f };
        // Wheel axle axis in wheel/knuckle local space.
        glm::vec3 axle_axis{ 0.0f, 0.0f, 1.0f };

        // Local anchor on the wheel body (useful if origin is not the hub center).
        glm::vec3 wheel_local_anchor{ 0.0f };

        // Suspension rest length along suspension_axis (positive along the axis).
        float suspension_rest_length = 0.0f;
        // Total suspension travel distance (symmetric around rest length).
        float suspension_travel = 0.5f;

        float spring_k = 15000.0f;
        float spring_d = 1500.0f;

        // Defaults for autogenerated colliders.
        float wheel_radius = 0.35f;
        float knuckle_radius = 0.15f;

        bool steerable = false;
        bool driven = false;
        float drive_direction = 1.0f;

        // Optional pre-existing wheel entity (if bound, builder will reuse it).
        EntityRef wheel{};
    };

    struct VehicleSpec
    {
        // Required chassis entity ref (must resolve to a live entity).
        EntityRef chassis{};
        // Optional root entity for grouping (if unbound, a new root is created).
        EntityRef root{};

        std::string name_prefix = "Vehicle";
        std::string chunk_tag = "vehicle_rig";
        std::vector<VehicleWheelSpec> wheels;

        // Create intermediate knuckle bodies between chassis and wheels.
        bool use_knuckle = true;
        // Kinematic knuckle helps stability with large mass ratios, but disables suspension forces.
        bool kinematic_knuckle = false;
        bool disable_collisions = true;

        // Steering hinge axis in chassis local space.
        glm::vec3 steer_axis{ 0.0f, 1.0f, 0.0f };
        float steer_limit = 0.8f;
        float steer_motor_target_velocity = 2.5f;
        float steer_motor_max_impulse = 250.0f;

        float drive_motor_target_velocity = 25.0f;
        float drive_motor_max_impulse = 750.0f;

        // Optional model asset names (lookup via ResourceManager asset index).
        std::string chassis_model_name{};
        std::string wheel_model_name{};
        std::string knuckle_model_name{};
    };

    struct VehicleRig
    {
        EntityRef root{};
        EntityRef chassis{};

        struct WheelRig
        {
            EntityRef knuckle{};
            EntityRef wheel{};
            EntityRef suspension_slider{};
            EntityRef suspension_spring{};
            EntityRef suspension_6dof{};
            EntityRef steering_hinge{};
            EntityRef axle_hinge{};
        };

        std::vector<WheelRig> wheels;
    };

    // Build a vehicle rig using the current ECS physics components.
    VehicleRig build_vehicle_rig(EngineContext& ctx, const VehicleSpec& spec);
} // namespace eeng::ecs
